# Generated by Django 5.2.6 on 2025-09-15 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
