# Generated by Django 5.2.6 on 2025-09-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0004_alter_journalentry_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={},
        ),
    ]
