# Generated by Django 5.2.6 on 2025-11-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0005_alter_journalentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='playlist_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
