# Generated by Django 5.2.6 on 2025-11-19 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0006_journalentry_playlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
