# Generated by Django 5.2.6 on 2025-12-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0007_journalentry_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
