# Generated by Django 5.2.6 on 2025-12-09 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0010_alter_comment_options_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_compound', models.FloatField(blank=True, null=True)),
                ('profile_pic_url', models.URLField(blank=True)),
                ('display_name', models.CharField(blank=True, max_length=30, null=True)),
                ('use_display_name', models.BooleanField(default=False)),
                ('text_size', models.CharField(default='16px', max_length=10)),
                ('text_color', models.CharField(default='#000000', max_length=20)),
                ('font', models.CharField(default='Verdana', max_length=100)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
