# Generated by Django 5.2.6 on 2025-12-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='text_size',
        ),
        migrations.AlterField(
            model_name='profile',
            name='font',
            field=models.CharField(choices=[('Segoe UI', 'Segoe UI'), ('Arial', 'Arial'), ('Verdana', 'Verdana'), ('Helvetica Neue', 'Helvetica Neue'), ('Sans-serif', 'Sans-serif'), ('Monospace', 'Monospace'), ('Open Sans', 'Open Sans'), ('Helvetica', 'Helvetica'), ('Georgia', 'Georgia'), ('Font Awesome', 'Font Awesome')], default='Segoe UI', max_length=50),
        ),
    ]
