# Generated by Django 5.2.6 on 2025-12-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0012_remove_profile_text_size_alter_profile_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='instrumentalness',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
