# Generated by Django 5.2.6 on 2025-12-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0013_journalentry_instrumentalness'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='use_instrumentalness',
            field=models.BooleanField(default=False),
        ),
    ]
