# Generated by Django 5.2.6 on 2025-12-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0014_journalentry_use_instrumentalness'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='accousticness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='liveness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='use_acousticness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='use_liveness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='use_popularity',
            field=models.BooleanField(default=False),
        ),
    ]
