# Generated by Django 5.2.6 on 2025-12-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0015_journalentry_accousticness_journalentry_liveness_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='accousticness',
            new_name='acousticness',
        ),
    ]
