# Generated by Django 5.2.6 on 2025-12-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0016_rename_accousticness_journalentry_acousticness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='acousticness',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='liveness',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='use_acousticness',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='use_liveness',
        ),
    ]
