# Generated by Django 5.2.6 on 2025-12-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0017_remove_journalentry_acousticness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
