# Generated by Django 5.2.6 on 2025-12-12 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0018_alter_journalentry_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='instrumentalness',
            new_name='liveness',
        ),
        migrations.RenameField(
            model_name='journalentry',
            old_name='use_instrumentalness',
            new_name='use_liveness',
        ),
    ]
