# Generated by Django 5.2.6 on 2025-12-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listenapp', '0019_rename_instrumentalness_journalentry_liveness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='instrumentalness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='use_instrumentalness',
            field=models.BooleanField(default=False),
        ),
    ]
